default:
  target: default
  outputs:
    default:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"

      role: "{{ env_var('SNOWFLAKE_ROLE', '') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'YOU_NEED_TO_CREATE_A_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'DBT') }}"

      threads: 5
      client_session_keep_alive: False
